services:
  web:
    build: .
    container_name: customizable-ecommerce-website
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PAYPAL_MODE=sandbox 
      - SESSION_SECRET=${SESSION_SECRET}
      - SITE_URL=http://localhost:3000
      - STORE_NAME=${STORE_NAME}
      - STORE_CURRENCY=INR         
      - TAX_PERCENT=0
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - ENABLE_COD=true  
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    networks: 
      - webnet
  postgres:
    image: postgres:16.15-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"          # optional (needed only if you want to connect from your host machine)
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
networks:
  webnet:

    



