pipeline {
    agent any
    environment {
        DOTENV_CREDENTIALS_ID = 'prod-dotenv'   // Jenkins Credentials -> Secret file ID            
  }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/MonuJangra-git/product_website_deploy.git'
            }
        }
        stage('Load .env at runtime only ') {
            steps {
                script{
                   withCredentials([file(credentialsId: env.DOTENV_CREDENTIALS_ID, variable: 'DOTENV')]) {

                    sh '''
                        cp "$DOTENV" .env
                        chmod 600 .env
                        echo ".env file copied successfully from Jenkins credentials to the workspace."
                    '''

                   
                    }

                }
            }
        }

        stage('List files') {
            steps {
                sh 'ls -la'
            }
        }

        // stage('Copy .env') {
        //     steps {
        //         sh 'cp /${PATH_TO_ENV}/.env ./'
        //         echo "Copied .env file copied successfully from the source to the destination."
        //     }
        // } //this is older method not safe and not recommended, using Jenkins credentials is better

        stage('Start Postgres') {
            steps {
                sh 'docker compose --env-file .env up  -d  postgres '
                echo "Postgres container started successfully."
            }
        }

        stage('Build & Start Web') {
            steps {
                sh 'docker compose --env-file .env build web'
            }
        }

        stage('Run Drizzle Push') {
            steps {
                sh 'docker compose --env-file .env run --rm web sh -lc "npx drizzle-kit push" '
            }
        }

        stage('Restart Compose') {
            steps {
                sh 'docker compose --env-file .env up  -d  web'
            }
        }
    }
    post {
        always {
            sh 'rm -f .env || true'
            echo ".env removed from workspace."
        }
    }
}